apiVersion: v1
kind: Service
metadata:
  name: springboot-api
spec:
  selector:
    app: springboot-app  # Must match the label on the Deployment pod
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

