name: Container Security Scan

on:
  push:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.trivy-scan.outcome != 'failure'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Scan Docker image for vulnerabilities
        id: trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Send email if vulnerabilities are found
        if: steps.trivy-scan.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Security Scan Failed: Vulnerabilities Detected"
          to: recipient@example.com
          from: Security Scanner <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Security scan failed!

            Critical or high vulnerabilities were found in the Docker image during the GitHub Actions workflow run.

            View details:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Push image to Docker Hub
        if: steps.trivy-scan.outcome == 'success'
        run: |
          docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
