name: Container Security Scan

on:
  push:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t cncf-cloud-native-security:latest .
        run: docker build -t cncf-cloud-native-security:latest .

      - name: Scan Docker image for vulnerabilities
        id: trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cncf-cloud-native-security:latest
          image-ref: cncf-cloud-native-security:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Log in to Docker Hub
        if: steps.trivy-scan.outcome == 'success'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: steps.trivy-scan.outcome == 'success'
        run: |
          docker tag cncf-cloud-native-security:latest ${{ secrets.DOCKERHUB_USERNAME }}/cncf-cloud-native-security:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cncf-cloud-native-security:latest

      - name: Send email if vulnerabilities are found
        if: steps.trivy-scan.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Security Scan Failed: Vulnerabilities Detected"
          to: ${{ github.event.head_commit.author.email }}
          from: Security Scanner <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello ${{ github.event.head_commit.author.name }},

            Security scan failed for your recent commit to the `${{ github.repository }}` repository.

            🔒 Critical or high vulnerabilities were found in the Docker image.

            📄 Commit: ${{ github.event.head_commit.message }}
            👤 Author: ${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>

            🔗 View details:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Fail the job explicitly if scan failed
        if: steps.trivy-scan.outcome == 'failure'
        run: exit 1
